name: HomeBudgeter
options:
  bundleIdPrefix: com.homebudgeter
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual

targets:
  HomeBudgeter:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: HomeBudgeter
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.homebudgeter.app
        PRODUCT_NAME: Home Budgeter
        INFOPLIST_FILE: HomeBudgeter/Resources/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: "Home Budgeter"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright 2024 Home Budgeter Team"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
        SWIFT_EMIT_LOC_STRINGS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_HARDENED_RUNTIME: true
        ENABLE_PREVIEWS: true
        COMBINE_HIDPI_IMAGES: true
    dependencies:
      - package: Supabase
        product: Supabase
    entitlements:
      path: HomeBudgeter/Resources/HomeBudgeter.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true

  HomeBudgeterTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: HomeBudgeterTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.homebudgeter.tests
        PRODUCT_NAME: HomeBudgeterTests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Home Budgeter.app/Contents/MacOS/Home Budgeter"
        BUNDLE_LOADER: "$(TEST_HOST)"
        SWIFT_VERSION: "5.9"
    dependencies:
      - target: HomeBudgeter

schemes:
  HomeBudgeter:
    build:
      targets:
        HomeBudgeter: all
        HomeBudgeterTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HomeBudgeterTests
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
